name: aidhs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.4.3
  - statsmodels=0.14.0
  - scikit-learn=1.2.2
  - notebook
  - matplotlib=3.5.1
  - h5py=3.9.0
  - nibabel=5.1.0
  - numpy=1.22.4
  - scipy=1.7.3 
  - pillow=9.2.0
  - seaborn=0.11.0
  - ptitprince=0.2.7
  - pip
  - pickleshare=0.7.5
  - pip:
    - neuroCombat==0.2.12
    - fpdf==1.7.2
    - joblib==1.2.0
    - potpourri3d==0.0.7
    - simpleITK==2.2.0
    - scikit-image==0.21.0
    - pybids==0.16.4
    - pytest==8.3.2
